{
  "headers": {
    "client_id": "c0f7de5d67de40febe8a6ce17ddcf13d",
    "client_secret": "af4DA819F52240Bb9E9767E19fC7dD1C",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "postman-token": "696f4d35-65c8-4015-b195-6bef402cfa13",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "143"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/movies",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/movies",
  "listenerPath": "/api/*",
  "relativePath": "/api/movies",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/movies",
  "rawRequestPath": "/api/movies",
  "remoteAddress": "/127.0.0.1:51430",
  "requestPath": "/api/movies"
}